name = "focusbox-dev"
compatibility_date = "2024-10-01"

[assets]
directory = "./dist"

[env.production]
route = "focusbox.dev/*"

[env.production.build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[[env.production.build.upload]]
format = "directory"
dir = "dist"